### ISSUE TITLE
Strange use of std::vector::clear/resize

### ISSUE THREAD

**Issue by devreal** [LLNL/LULESH#4]
I am currently working on a port of Lulesh and noticed a strange usage of the combination of `std::vector::clear` and `std::vector::resize`, which is used for managing temporary buffers for strains and gradients. As an example, the comment in this line https://github.com/LLNL/LULESH/blob/master/lulesh.cc#L2018 states `Free up memory` but the following call to `std::vector::clear` does not actually free the memory. The standard mandates that the number of elements in the vector is set to 0 and the capacity is left unchanged [1]. The next call to `std::vector::resize` will find the capacity to be sufficient (as `numElem` does not change) and initialize all elements in the vector to 0.0 (essentially acting as `memset`), something that does not seem to be needed as the values are later overwritten anyway. In my benchmarks, this leads to some noticeable overhead (e.g., ~15% on 8 ranks/24threads on our XC40, 256**3 elements per rank) that seems easily avoidable. 

Hence my question: is the reset of the gradient and strain temporaries an essential part of the benchmark or is it a valid optimization to either make these buffers static or use `Allocate`/`Release` on them instead?

[1] https://en.cppreference.com/w/cpp/container/vector/clear

**Comment by ikarlin** [comment]
You are correct this is not the correct way to handle what is intended by this code.  The intention is to have the memory deleted then reallocated.  This is to mimic the needed behavior in production codes.  The alternative is to use memory pools and some of our production codes are moving in that direction.

So to answer your question its not a valid optimization in a production sense to just use static buffers.  However, it is OK to Allocate/Release them and this is what the code should be doing.  If you have a suggested solution feel free to put in a pull request.   Otherwise, I'll work on this at some point.

Note we have looked at just making these static and using a pooled allocator on CPU https://e-reports-ext.llnl.gov/pdf/710738.pdf .  Using tcmalloc was good enough to solve the problem.  People are working on pooled allocators in the context of the production code on GPUs.

**Comment by ikarlin** [comment]
[Pull request 8](https://github.com/LLNL/LULESH/pull/8) solves this issue.
